# Dockerfile

# 1. Imagem base do Python
FROM python:3.10.12-slim-buster

# 2. Configurações de ambiente para o Python
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# 3. Define o diretório de trabalho dentro do container
WORKDIR /usr/src/app

# 4. Copia o arquivo de dependências e as instala
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# 5. Copia todo o código do seu projeto para o diretório de trabalho
COPY . .

# 6. Expõe a porta 8000 para que possamos acessá-la de fora
EXPOSE 8000